In [1]:
import numpy as np

In [6]:
arr_np = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14,3]])

In [7]:
arr_np

array([list([0, 1, 2, 3, 4]), list([5, 6, 7, 8, 9]),
       list([10, 11, 12, 13, 14, 3])], dtype=object)

In [11]:
print("Dimension:", arr_np.ndim,"Shape:",arr_np.shape)

Dimension: 1 Shape: (3,)


In [ ]:
#CREATE ARRAY ZEROES (row, column)

In [52]:
arr2_np = np.zeros((3,2))

In [54]:
arr2_np

print ('dim',arr2_np.ndim,'shape',arr2_np.shape)

dim 2 shape (3, 2)


In [18]:
print("Dimension:", arr2_np.ndim,"Shape:",arr2_np.shape)

Dimension: 2 Shape: (3, 2)


In [26]:
# CREATE ARRAY ONES 3 dimension (?,rows, columns)
arr3_np = np.ones((2,3,4))

In [27]:
arr3_np

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
#Array kosong
array_kosong = np.empty((2,3))
print(array_kosong)

[[2.18254130e-289 5.02034658e+175 7.62340979e+169]
 [6.11705533e+169 7.17049755e-038 1.68822422e-051]]


In [29]:
array_kosong

array([[2.18254130e-289, 5.02034658e+175, 7.62340979e+169],
       [6.11705533e+169, 7.17049755e-038, 1.68822422e-051]])

In [30]:
array_kosong[0][0]

2.1825413012454354e-289

In [41]:
#Array with pola
#Array 1d Dengan from 10, to 30, add5 (10,30,5)
arr1d_arange = np.arange(10,30,5)

In [42]:
arr1d_arange

array([10, 15, 20, 25])

In [44]:
#Array 1d Dengan 9 bilangan, dari 0 sampai 2  (0,2,9)
arr1d_arange_linspace = np.linspace(0,2,9)

In [46]:
arr1d_arange_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [48]:
print ('dim',arr1d_arange_linspace.ndim,'shape',arr1d_arange_linspace.shape)

dim 1 shape (9,)
